### ISSUE TITLE
Allow running as a user other than root.

### ISSUE THREAD

**Issue by kbaltrinic** [pghalliday-cookbooks/sonarqube#3]
Presently the cookbook installs SonarQube such that it runs as root.  It would be nice if there were a sonarqube.user attribute that could specify the account under which SonarQube will be run.

**Comment by pghalliday** [comment]
version 0.2.0 released - runs as `sonarqube` user by default

**Comment by kbaltrinic** [comment]
Now that's what I call service with a smile!  Thanks!
