### ISSUE TITLE
Ability to configure SonarQube plugins broken by  53a4c49

### ISSUE THREAD

**Issue by kbaltrinic** [pghalliday-cookbooks/sonarqube#7]
The changes made in Commit 53a4c49 break the ability to configure any server properties that are not already anticipated in the properties file template.  Specifically it now becomes impossible to specify LDAP  plugin settings, or any other settings that another plug-in may add to the server config.

If one attempts to replace the sonar.properties file with a different one (base on our own template, custom to our needs) it results in a tug-o-war at every converge where the base sonarqube write the file one way, our cookbook writes it back to our way and the resulting change causes the service to restart.

**Comment by kbaltrinic** [comment]
A simple solution to this would be to split out the sonar-installation steps and the sonar-configuration steps into separate recipes and then invoke both in the default recipe.  This retains the current default functionality but allow those who need to use the installation recipe independent of the configuration recipe and do the configuration themselves.

**Comment by pghalliday** [comment]
It's also possible to specify additional configuration such as LDAP through the `extra_properties` attribute. Does that not work for your use case?

**Comment by kbaltrinic** [comment]
Sorry I missed that one when scanning the attributes file.  Yes that looks like it should work.
