### ISSUE TITLE
Default mirror needs updating: codehaus.org is defunct.

### ISSUE THREAD

**Issue by kbaltrinic** [pghalliday-cookbooks/sonarqube#8]
Now the codehaus.org has shut down, sonarqube is being hosted on bintray.  The current values that work for me are

    default['sonarqube']['mirror'] = 'https://sonarsource.bintray.com/Distribution/sonarqube/'
    default['sonarqube']['version'] = '5.1.2'
    default['sonarqube']['checksum'] = 'a8d63d837242d0d07c0b3f65cfa9c84d5ae82ee51c6cbb52248bcf0d1bc58491'

Not sure if the `Distribution/sonarqube` part should be considered part of the mirror or not but at least the above works w/o having to modify the recipe.

**Comment by pghalliday** [comment]
ok updated in version 0.3.1
