### ISSUE TITLE
A better way to implement derived attributes.

### ISSUE THREAD

**Issue by kbaltrinic** [pghalliday-cookbooks/sonarqube#9]
Sorry its me again.  :)  I just learned how to do this better myself and wanted to pass it along.  The derived ['sonarqube']['config']['dir'] attribute on [Line 6](https://github.com/pghalliday-cookbooks/sonarqube/blob/master/attributes/default.rb#L6) of the attributes/default.rb is problematic and  I have had to code around it.   The following article details why and how to fix: https://coderanger.net/derived-attributes/ and I thought it would be a great little fix.

Regards.

**Comment by pghalliday** [comment]
i like it :) will have to test it though

**Comment by pghalliday** [comment]
ok done and published in 0.3.2, thanks for the tip
